service: hello-crud

provider:
  stackName: "${self:custom.prefix}-${self:service}"
  runtime: nodejs8.10
  name: aws
  stage: ${self:custom.prefix}
  deploymentBucket:
    name: ${self:custom.env.bucketName}
  apiGateway:
    restApiId: ${self:custom.env.restApiId}
    restApiRootResourceId: ${self:custom.env.restApiRootResourceId}

functions:
  HelloRead:
    handler: handler.hello
    name: "${self:custom.prefix}-get"
    description: Get the current calculator state
    memorySize: 128
    timeout: 5

resources:
  Resources:
    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId: ${self:custom.env.restApiId}
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId:
          Ref: ApiGatewayDeployment
        RestApiId: ${self:custom.env.restApiId}
        StageName: ${self:custom.prefix}
        Variables:
          getHelloFunction: "${self:custom.prefix}-get"
    ReadFunctionPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: 
          Ref: HelloReadLambdaFunction
        Principal: apigateway.amazonaws.com
        SourceArn: 
          !Join
            - ':'
            - - 'arn:aws:execute-api'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - ${self:custom.env.restApiId}/*/GET/hello

custom:
  env: ${file(./${opt:file}.yml)}
  prefix: ${opt:prefix, 'calcs-test'}