service: hello-world-lambdas

provider:
  name: aws
  runtime: nodejs12.x
  stackName: "${self:service}-${self:custom.stage}"
  stage: ${self:custom.stage}
  deploymentBucket:
    name: 'hello-salinn-serverless-deployments'

functions:
  Hello:
    handler: src/hello.handler
    name: "hello-${self:custom.stage}"
    description: Say hello to the world or a person
    memorySize: 128
    timeout: 5

resources:
  Resources:
    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId: ${self:custom.restApiId}
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId:
          Ref: ApiGatewayDeployment
        RestApiId: ${self:custom.restApiId}
        StageName: ${self:custom.stage}
        Variables:
          helloFunction: "hello-${self:custom.stage}"
    HelloLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: 
          Ref: HelloLambdaFunction
        Principal: apigateway.amazonaws.com
        SourceArn: ${self:custom.apiGatewayHelloFunctionArn}

custom:
  stage: ${opt:stage, 'recipe-fb'}
  apiGatewayStage: ${opt:apiGatewayStage, ${self:custom.stage}}
  restApiId: 
    Fn::ImportValue:
      Fn::Sub: "hello-gateway-${self:custom.apiGatewayStage}-restApiId"
  apiGatewayHelloFunctionArn: 
    Fn::ImportValue:
      Fn::Sub: "hello-gateway-${self:custom.apiGatewayStage}-hello-function-arn"