service: hello-crud

provider:
  stackName: "${self:custom.stage}-${self:service}"
  runtime: nodejs8.10
  name: aws
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.env.bucketName}

functions:
  HelloRead:
    handler: handler.hello
    name: "${self:custom.stage}-get"
    description: Get the current calculator state
    memorySize: 128
    timeout: 5

resources:
  Resources:
    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId: ${self:custom.env.restApiId}
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId:
          Ref: ApiGatewayDeployment
        RestApiId: ${self:custom.env.restApiId}
        StageName: ${self:custom.stage}
        Variables:
          getHelloFunction: "${self:custom.stage}-get"
    ReadFunctionPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: 
          Ref: HelloReadLambdaFunction
        Principal: apigateway.amazonaws.com
        SourceArn: 
          !Join
            - ':'
            - - 'arn:aws:execute-api'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - ${self:custom.env.restApiId}/*/GET/hello

custom:
  env: ${file(./${opt:env}.yml)}
  stage: ${opt:stage, 'hello-test'}